#
# Module manifest for module 'WhisperSubtitle'
#
# Generated by: Notso AI
#
# Generated on: 10-5-2025
#

@{
	# Module metadata
	RootModule           = 'WhisperSubtitle.psm1'
	ModuleVersion        = '0.1.0'
	GUID                 = '8d8bd1ba-3422-5ec4-aecc-f19af28d2cf1'

	# Author and company information
	Author               = 'Kaj Kowalski'
	CompanyName          = 'kjanat'
	Copyright            = '(c) 2025. All rights reserved.'

	# Module description
	Description          = 'Professional subtitle generation module using OpenAI Whisper with advanced features for video processing, multiple output formats, and batch operations.'

	# Minimum PowerShell version
	PowerShellVersion    = '7'

	# Required modules and assemblies
	RequiredModules      = @()
	RequiredAssemblies   = @()

	# Script files and type files
	ScriptsToProcess     = @() # Script files (.ps1) that are run in the caller's environment prior to importing this module.
	TypesToProcess       = @() # Type files (.ps1xml) to be loaded when importing this module
	FormatsToProcess     = @() # Format files (.ps1xml) to be loaded when importing this module

	# Nested modules
	NestedModules        = @() # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess

	# Functions to export from this module
	# For best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
	FunctionsToExport    = @(
		'ConvertTo-Subtitle',
		'Get-WhisperModuleInfo',
		'Get-WhisperSubtitleConfig',
		'Set-WhisperSubtitleConfig'
	)

	# Cmdlets to export from this module
	# For best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
	CmdletsToExport      = @()

	# Variables to export from this module
	VariablesToExport    = @()

	# Aliases to export from this module
	# For best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
	AliasesToExport      = @('whisperSub')

	# DSC resources
	DscResourcesToExport = @()

	# List of all modules packaged with this module
	ModuleList           = @()

	# List of all files packaged with this module
	FileList             = @(
		'WhisperSubtitle.psm1',
		'WhisperSubtitle.psd1',
		'Private\Get-ModuleConfig.ps1',
		'Private\Set-ModuleConfig.ps1',
		'Public\Get-WhisperSubtitleConfig.ps1',
		'Public\Set-WhisperSubtitleConfig.ps1'
	)

	# Private data to pass to the module specified in RootModule/ModuleToProcess.
	# This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData          = @{
		PSData = @{
			# Tags applied to this module.
			# These help with module discovery in online galleries.
			Tags                       = @('Whisper', 'Subtitles', 'Video', 'AI', 'Transcription', 'Speech-to-Text')

			# License and project URLs
			# A URL to the license for this module.
			LicenseUri                 = 'https://github.com/kjanat/WhisperSubtitle/blob/master/LICENSE'
			# A URL to the main website for this project.
			ProjectUri                 = 'https://github.com/kjanat/WhisperSubtitle'
			IconUri                    = 'https://github.com/kjanat/WhisperSubtitle/raw/master/Assets/icon.svg'

			# Release notes
			ReleaseNotes               = @'
Version 0.1.0:
- Complete rewrite as professional PowerShell module
- Enhanced error handling and logging
- Support for pipeline processing
- Improved parameter validation
- Added progress tracking
- Modular architecture with helper functions
- Better prerequisite checking
- Advanced subtitle optimization
- Comprehensive documentation
'@

			# Prerelease information
			# Prerelease = 'alpha'

			# External module dependencies
			ExternalModuleDependencies = @()
		}
	}

	# Help info URI
	HelpInfoURI          = ''

	# Default command prefix
	DefaultCommandPrefix = ''
}
