name: Documentation Generation

# Review gh actions docs if you want to further define triggers, paths, etc
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      test:
        description: "Skip deployment to GitHub Pages"
        type: boolean
        default: false
        required: false

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: ${{ (github.event_name == 'pull_request') && format('test-deploy-{0}', github.event.number) || (github.event_name == 'workflow_dispatch' && inputs.test) && 'test-deploy-manual' || 'deploy' }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to read the repository contents
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docs
        uses: Microsoft/ps-docs@main
        with:
          inputPath: .            # Path to look for input files
          source: .ps-docs/       # Path containing document definitions
          outputPath: out         # Path to write documentation to
          path: .                 # Working directory for PSDocs
          prerelease: true        # Allow prerelease modules

      - name: Upload docs to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    name: Deploy to GitHub Pages
    needs: generate
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch' && !inputs.test)

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
